### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by 4s3ti** [abichinger/semantic-release-pypi#22]
Hi, 

Is there a way to skip the setup.py or use pyproject.toml instead?

**Comment by abichinger** [comment]
Hi,

at the moment semantic-release-pypi has some limitations
- it requires `setup.py`
- the version is always written into `setup.cfg`
- only supports setuptools to build

It should still be possible to have `pyproject.toml` alongside of `setup.py`.

Also, have you seen https://python-semantic-release.readthedocs.io/en/latest/? Maybe this package covers your needs.

**Comment by 4s3ti** [comment]
alright, thank you @abichinger for your time. in the meantime got some workaround going on with some workaround and chore commit before building and publishing.
