### ISSUE TITLE
If pyproject.toml does not have a project attribute, an error will be reported

### ISSUE THREAD

**Issue by leeqvip** [abichinger/semantic-release-pypi#31]
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/node/18.18.2/x64/lib/node_modules/semantic-release-pypi/dist/py/set_version.py", line 24, in <module>
    toml['project']['version'] = args.version
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/tomlkit/container.py", line 613, in __getitem__
    raise NonExistentKey(key)
tomlkit.exceptions.NonExistentKey: 'Key "project" does not exist.'
```

**Comment by abichinger** [comment]
Hey @leeqvip

`semantic-release-pypi` needs a `project` or a `tool.poetry` section to set the version.
If you have neither in your `pyproject.toml` file, this is the expected error.

Your PR #32 would get rid of the error, but the version would no longer be updated.

Please explain to me why you need this?

**Comment by leeqvip** [comment]
In my project, `pyproject.toml` is only used for `lint` checking, and the version is still configured in `setup.cfg`

**Comment by abichinger** [comment]
I see. I can think of two solutions

1. add a new option, which allows the user to force set the build interface (`pyproject.toml` or `setup.py`)
2. use `semantic-release-pypi@2.5.2` - this version will always set the version in `setup.cfg`

**Comment by abichinger** [comment]
I'm happy to make a PR on pycasbin to fix the release workflow if you'd like.

**Comment by leeqvip** [comment]
> I'm happy to make a PR on pycasbin to fix the release workflow if you'd like.

Thanks !
