### ISSUE TITLE
feat: create virtual python environment to install dependencies

### ISSUE THREAD

**Issue by abichinger** [abichinger/semantic-release-pypi#34]

**Comment by CodyKurtz** [comment]
I would like to upvote this. I am running into an issue now, where dependency installation fails because I get the error message, “this environment is externally managed”. @abichinger do you have a workaround for this?

**Comment by abichinger** [comment]
> @abichinger do you have a workaround for this?

I think, creating a virtual environment before running semantic-release should work. (I have not tested this)
```sh
python -m venv .venv
source .venv/bin/activate
```

> It would be nice, if I could disable the automatic package installation and install the libraries myself.

I think I'm going to add the following two options:

| Option | Type | Default | Description
| ------ | ---- | ------- | -----------
| ```venv``` | string \| ```false``` | ```.venv``` | directory to create the virtual environment in, if set to `false` no environment will be created
| ```installDeps``` | bool | ```true``` | wether to automatically install python dependencies

**Comment by CodyKurtz** [comment]
Thank you @abichinger for the quick response. I’ll try this and update you here. I agree with both those parameters, they would be useful.

**Comment by CodyKurtz** [comment]
@abichinger using a virtual environment as you suggested fixed the issue. Thank you

**Comment by abichinger** [comment]
7c936a174eb5e55bbd2660f2bb9681b4062b4604
3e5104c47450e772b93c2b1577da50aa5ab8331f
