### ISSUE TITLE
python3: can't find '__main__' module in set_version.py

### ISSUE THREAD

**Issue by christianklemp** [abichinger/semantic-release-pypi#35]
I'm attempting to use this plugin with a docker image I've installed Python 3.12.2 on and am receiving the following error from semantic-release:

```
/usr/local/bin/python3: can't find '__main__' module in '.yarn/cache/semantic-release-pypi-npm-3.0.0-4729aab989-8a19134713.zip/node_modules/semantic-release-pypi/dist/py/set_version.py'
```

I've tried it with python 3.9.7, 3.10, 3.11, and 3.12 and run into the same error.

I'm using node 20.8.1, yarn 4.1.1, semantic-release 23.0.2, and semantic-release-pypi 3.0.0.

**Comment by abichinger** [comment]
Hello, 
looks like the file `set_version.py` is missing inside the container. Can you share your Dockerfile?

**Comment by christianklemp** [comment]
After further looking into this, it ended up being an issue with how yarn `nodeLinker` works by default with `pnp`. It began working once I added `nodeLinker: node-modules` to my `.yarnrc.yml` (I believe it was due to it trying to use a file out of a `zip` in `.yarn/cache`).
