### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by apaparazzi0329** [abichinger/semantic-release-pypi#8]
Not sure if this is an issue with semantic-release-pypi or some other issue but when running the `verifyConditions` step in a GHA ubuntu-latest CI environment utilizing PYPI_TOKEN we get this strange error with no feedback as to what may be causing it.
<img width="741" alt="Screen Shot 2021-06-22 at 2 50 39 PM" src="https://user-images.githubusercontent.com/26935099/122983187-b8c6df80-d369-11eb-9275-9174770ddbcf.png">

**Comment by abichinger** [comment]
I triggered a release ([log](https://github.com/abichinger/semantic-release-pypi-example/runs/2916832542?check_suite_focus=true)) of [semantic-release-pypi-example](https://github.com/abichinger/semantic-release-pypi-example). The workflow uses ubuntu-latest and it was successful.

Please provide the workflow and the complete log?

**Comment by abichinger** [comment]
closed due to inactivity
